# Generated by Django 5.2.6 on 2025-09-24 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "approved_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "current_debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_id", models.IntegerField(unique=True)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("tenure_months", models.IntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "monthly_installment",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("emis_paid_on_time", models.IntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "current"),
                            ("repaid", "repaid"),
                            ("default", "default"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="loans.customer",
                    ),
                ),
            ],
        ),
    ]
