# Generated by Django 5.2.6 on 2025-09-24 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="monthly_income",
            new_name="monthly_salary",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="age",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="monthly_installment",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="status",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="tenure_months",
        ),
        migrations.AddField(
            model_name="loan",
            name="monthly_repayment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="tenure",
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="approved_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="current_debt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="loan",
            name="emis_paid_on_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loan",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
